-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
#    -   id: end-of-file-fixer
#    -   id: trailing-whitespace
#    -   id: check-xml
